Fix ProGuard ParseException: Expecting class member name (#6)
* Fix the keepclassmembernames

> java.io.IOException: proguard.ParseException: Expecting class member name before ';' in line 2 of file

* Bump to 1.0.3